name: GitHub Issue Analytics

on:
  push:
    branches:
      - main  # Adjust the branch name to your default branch (e.g., "main" or "master")
      
jobs:
  analytics:
    runs-on: ubuntu-latest
    steps:
    
    # Step 1: Checkout the repository containing the GitHub Issue Analytics tool
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    # Step 2: Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install PyGithub pandas plotly
    
    # Step 4: Set GitHub Token as an environment variable
    - name: Set GitHub Token
      run: echo "MY_GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}" >> $GITHUB_ENV
    
    - name: Fetch GitHub Issue Data
      id: fetch_data
      run: |
        # Get today's date (Thursday)
        current_date=$(date -u +"%Y-%m-%d")
        
        # Get the previous Friday's date
        previous_friday=$(date -u -d 'last friday' +"%Y-%m-%d")
        
        # Extract year, month from the previous Friday
        year=$(date -u -d "$previous_friday" +"%Y")
        month=$(date -u -d "$previous_friday" +"%m")
        
        # Calculate the first day of the month
        first_day_of_month=$(date -u -d "$year-$month-01" +"%Y-%m-%d")
        
        # Get the day of the month for the previous Friday
        previous_friday_day=$(date -u -d "$previous_friday" +"%d")
        
        # Calculate the number of days between the first day of the month and the previous Friday
        days_diff=$(( ( $(date -u -d "$previous_friday" +%s) - $(date -u -d "$first_day_of_month" +%s) ) / 86400 ))
        
        # Calculate the week of the month based on the days difference
        week=$(( (days_diff) / 7 + 1 ))
        
        # Print the week calculation for debugging
        echo "Calculated week of the month: $week"
        
        # Run the fetch command without repository name
        echo "Running command: python fetch_github_data.py $year $month $week"
        python fetch_github_data.py $year $month $week



    # Step 6: Generate the report
    - name: Generate Report
      id: generate_report
      run: |
        DATA_FILE_PATH=$(python fetch_github_data.py $year $month $week ${{ github.event.inputs.repository }} | awk '/OUTPUT_FILE:/ {print $2}')
        python generate_report.py --data $DATA_FILE_PATH --output /tmp/github_issues_report.html
    
    # Step 7: Upload the report as an artifact (use latest version v4 of upload-artifact)
    - name: Upload Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-issues-report
        path: /tmp/github_issues_report.html
